import "./globals.css";
import Link from "next/link";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="w-full h-20 bg-slate-300">
          <Link href="/signup">Signup</Link>
          <Link href="/login">Login</Link>
        </div>
        {children}
      </body>
    </html>
  );
}
